### PR TITLE
[FIX] Fix header

### PR DESCRIPTION
**Pull request by RODRIGUErzed**
A merger request to correct the logo display on site

### CODE REVIEW

**Comment by RODRIGUErzed** [comment]
This is an image
A merge request to correct the logo error on the https://db-benchmarks.com/about/ website as shown in the image

**Comment by sanikolaev** [comment]
@RODRIGUErzed Hi. Does it fail for you with just `logo = "images/logo.svg"` ? Can you provide more detail on the failure?

**Comment by RODRIGUErzed** [comment]
I had to test the solution locally on a Windows as shown in the image and then modify to have the logo displayed, I also tested it on a Linux distribution we do not have the same problems, but with this solution we have the same solution on both distributions

**Comment by sanikolaev** [comment]
> I also tested it on a Linux distribution we do not have the same problems

Right, that's why I didn't notice it. The pull request is approved and the change has been merged. Thank you!

**Pull request merged**
